#!/bin/csh
GCC=/usr/local/bin/g++ -fhandle-exceptions -I.

all : assign2

assign2 : assign2.cpp String.o
	$(GCC) -o assign2 assign2.cpp String.o

String.o : String.cpp String.h
	$(GCC) -c String.cpp

clean :
	/bin/rm -f assign2 *.o
